[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd nahb-backend && npm install',
  'cd nahb-frontend && npm install'
]

[phases.build]
cmds = [
  'cd nahb-frontend && npm run build'
]

[start]
cmd = 'cd nahb-backend && npm start'
