[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install --prefix nahb-backend',
  'npm install --prefix nahb-frontend'
]

[phases.build]
cmds = [
  'npm run build --prefix nahb-frontend'
]

[start]
cmd = 'npm start --prefix nahb-backend'
